FROM node:8.11

# Build node_modules for kbh-billeder
WORKDIR /home/node/kbh-billeder
COPY projects/kbh-billeder/package*.json ./
RUN npm install --progress=false

# Build node_modules for collections-online
WORKDIR /home/node/collections-online
COPY projects/collections-online/package*.json ./
RUN npm link

# Build node_modules for collections-online-cumulus
WORKDIR /home/node/collections-online-cumulus
COPY projects/collections-online-cumulus/package*.json ./
RUN npm link

# Remove relative links and replace them with absolute.
WORKDIR /home/node/kbh-billeder/node_modules
RUN rm -rf collections-online && rm -rf collections-online-cumulus && \
    ln -s /usr/local/lib/node_modules/collections-online collections-online && ln -s /usr/local/lib/node_modules/collections-online-cumulus collections-online-cumulus
WORKDIR /home/node/collections-online-cumulus/node_modules
RUN rm -rf collections-online && ln -s /usr/local/lib/node_modules/collections-online collections-online
WORKDIR /home/node/collections-online/node_modules
RUN rm -rf collections-online && ln -s /usr/local/lib/node_modules/collections-online collections-online

# Move our entrypoint into place and register it.
WORKDIR /home/node/kbh-billeder

CMD /usr/local/bin/npm run start:dev

EXPOSE 9000
